# .rubocop.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7 # Adjust this to your Ruby version

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: ['RSpec.describe', 'describe', 'context', 'feature']

Style/FrozenStringLiteralComment:
  Enabled: false

# Customize other rules as needed
